<?php if ($this->message) {
  $halt = true;

  switch ($this->message){
    case "no_hash":
      $dk = "Dette link er ikke gyldigt";
      $en = "This link is not valid";
      break;
    case "registered":
      $dk = "Du har allerede registreret dine oplysninger";
      $en = "You've already registered your information";
      break;
    case "fail_pass":
      $dk = "Koden er ikke korrekt";
      $en = "The code isn't correct";
      $halt = false;
      break;
    case "success":
      $dk = "Dine oplysninger er nu gemt";
      $en = "Your information has been saved";
      break;
    case "empty_reg":
      $dk = "Registreringsnummer må ikke være tomt";
      $en = "Registration number cannot be empty";
      $halt = false;
      break;
    case "tolong_reg":
      $dk = "Registreringsnummer må ikke være længere end 4 cifre";
      $en = "Registration number cannot be longer than 4 digits";
      $halt = false;
      break;
    case "empty_acc":
      $dk = "Kontonummer må ikke være tomt";
      $en = "Account number cannot be empty";
      $halt = false;
      break;
    case "tolong_acc":
      $dk = "Kontonummer må ikke være længere end 18 cifre";
      $en = "Account number cannot be longer than 18 digits";
      $halt = false;
      break;
    default:
      $dk = "Ukendt fejl";
      $en = "Unknow error";
  }

  if (!$halt){
    $class = 'class="refund-error"' ;
  }
}?> 

<div class="refund">
<?php
$mail = "bunker@fastaval.dk";
$mail_url = "<a href='mailto:$mail'>$mail</a>";
if(!$this->participant || $this->participant->speaksDanish()) { 
  ?>
    <h2>Fastaval 2020 Tilbagebetaling</h2>
    <div <?=$class?>><?=$dk?></div>
  <?php if($halt) {?>
    <p>Hvis du har brug for hjælp kan du skrive til <?=$mail_url?></p>
  <?php }
}

if(!$this->participant || !$this->participant->speaksDanish()) { 
  ?>
    <h2>Fastaval 2020 Refund</h2>
    <div <?=$class?>><?=$en?></div>
  <?php if($halt) {?>
    <p>If you need help you can send a mail to <?=$mail_url?></p>
  <?php }
}

if ($this->participant && $this->participant->speaksDanish()) {
  $saved = "Dette er hvad vi har gemt:";
  $code = "Kode";
  $reg = "Bank registreringsnummer";
  $account = "Bankkontonummer";
  $alea = "Forbliv medlem af Alea (koster 75 kr.)";
  $sub = "Submit";
  $yes = "Ja";
  $no = "Nej";
  $bankheader = <<<HTML
  <h3>Bankoplysninger</h3>
  <p><b>NB: Det er kontonummer og IKKE kortnummer</b></p>
HTML;
} else {
  $saved = "This is the information we have saved:";
  $code = "Code";
  $reg = "Bank registration number";
  $account = "Bank account number";
  $alea = "Stay a memeber of Alea (costs 75 DKK)";
  $sub = "Submit";
  $yes = "Yes";
  $no = "No";
  $bankheader = <<<HTML
  <h3>Bank information</h3>
  <p><b>Attention: We need you bank account number and not you card number</b></p>
HTML;
}

if ($this->message == "success" || $this->message == "registered") { ?>
  <p><?=$saved?></p>
  <table>
    <tr>
      <td><?=$reg?></td>
      <td>: <?=sprintf("%04d", $this->participant->refund_reg)?></td>
    </tr>
    <tr>
      <td><?=$account?></td>
      <td>: <?=$this->participant->refund_account?></td>
    </tr>
    <tr>
      <td><?=$alea?></td>
      <td>: <?=$this->participant->refund_stay_alea === "ja" ? $yes : $no ?></td>
    </tr>
  <table>
<?php }

if ($halt) return;

?>

<?php if ($this->participant->speaksDanish()) { ?>
  <p>Velkommen <?=$this->participant->getName()?>
  <p>Brug koden fra den bekræftelsesmail du fik da du tilmeldte dig Fastaval</p>
  <p>Det er vigtigt at du kontrollerer oplysningerne inden du sender dem, da det
  vil være besværligt at rette efterfølgende</p>
  <p>Hvis du har brug for hjælp kan du skrive til <?=$mail_url?></p>
<?php } else { ?>
  <p>Welcome <?=$this->participant->getName()?>
  <p>Use the code included in the confirmation mail you got when you signed up for
  Fastaval</p>
  <p>It's important that you check the information before submitting it, since
  it will be difficult to change afterwards</p>
  <p>If you don't have a danish bank account or you need help, please send a
  mail to <?=$mail_url?></p>
<?php } ?>
  <form method="post">
    <label><?=$code?>
      <input type="text" name="code" size="6" value="<?=$this->request->post->code?>">
    </label>
    <?=$bankheader?>
    <label><?=$reg?>
      <input id="refund_reg" type="number" class="no-arrows" name="reg" maxlength="4" size="4" value="<?=$this->request->post->reg?>">
    </label>
    <br>
    <label><?=$account?>
      <input id="refund_acc" type="number" class="no-arrows" name="account" maxlength="18" size="18" value="<?=$this->request->post->account?>">
    </label>
    <br>
<?php if ($this->participant->calcAlea() > 0) {?>    
    <label><?=$alea?>
      <input type="checkbox" name="alea" <?=$this->request->post->alea ? "checked" : "" ?>>
    </label>
    <br>
<?php } ?>
    <input type="submit" value="<?=$sub?>">
  </form>
</div>
