<?php if ($this->danish) { ?>
<h2>Fastaval 2020 Tilbagebetaling</h2>

<h3>Der var desværre en fejl i linket i den føste mail, så her er en mail med et
nyt link.</h3>

<p>Kære deltager til Fastaval 2020</p>

<p>Fastaval 2020 er aflyst og bunkeren påbegynder nu den store opgave, der
ligger i at refundere alle forudbetalinger til Fastaval. Du vil få alle dine
penge retur, med mindre du har købt bogen Mulm eller ønsker at blive medlem af
Alea, foreningen der arrangerer Fastaval.</p>

<h3>Hvad du skal gøre</h3>

<p>I bunden af denne mail, finder du et personligt link til en
refunderings-side. Her skal du indtaste en række oplysninger, som vi har brug
for, for at kunne sende dine penge retur. Inde i linket får du brug for den
kode, du fik tilsendt, da du tilmeldte dig Fastaval. Koden står i mailen med
navnet “Tilmelding til Fastaval 2020” i emnefeltet og du finder koden ca. midt
i mailen.</p>

<p>På refunderings-siden skal du blandt andet oplyse dit kontonummer og tage
stilling til, om du ønsker at være medlem af Alea eller ej. Siden kan kun bruges
med et dansk kontonummer. Har du ikke sådan et, skal du i stedet skrive til 
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a>, så finder vi en
løsning.</p>

<h3>Fastavals økonomi</h3>

<p>Fastaval og Alea har en stærk økonomi og det er ikke noget problem at
tilbagebetale alle fuldt ud. Vi har været utroligt heldige med 
samarbejdspartnere, som alle har haft stor forståelse for den specielle
situation vi står i. De har uden at blinke annulleret vores aftaler og ikke
rejst nogle krav om erstatning.</p>

<p>Flere deltagere har givet udtryk for, at de ikke ønsker at få deres betaling
retur, men i stedte vil støtte Fastaval 2021. Vi er både glade og rørte for at
få så meget opbakning til Fastaval, men din finansielle støtte er heldigvis ikke
nødvendigt. Vi vil i stedet opfordre til at I forsøger at støtte vores faste
samarbejdspartnere, hvor især Danhostel Hobro og Hotel America er hårdt ramt af
nedlukningen.</p>

<p>Det bedste du kan gøre for at støtte Fastaval fremadrettet er at blive medlem
af Alea.</p>

<h3>Bliv medlem af Alea</h3>

<p>Alea er foreningen bag Fastaval og under normale omstændigheder får Alea
langt de fleste af sine medlemmer gennem Fastavaltilmeldingen. Vi håber at du
stadig har lyst til at være medlem af Alea, selv om du ikke får den vanlige
rabat.</p>

<p>Alea bruger dit medlemskontingent på at drive organisationen, der driver
Fastaval. Udover den administrative del, afholder Alea også en masse
arrangementer mellem hver Fastaval – generalforsamlingen,
forfatter/designer-weekender og arrangørweekender. Alea skaber stabilitet og
kontinuitet mellem årlige Fastavaller, skiftende bunkere og vores mange faste
samarbejder i Hobro og andre steder.</p>

<p>Derudover er Alea medlem af landsorganisationen Bifrost. Bifrost får årlig
støtte fra Dansk Ungdoms Fællessråd der blandt andet er påvirket af hvor mange
Alea-medlemmer der er. Tilskudet bruger de på at støtte rollespil i hele Danmark
(inklusiv Fastaval), og lave lobbyarbejde til gavn for det danske
rollespilsmiljø.</p>

<p>Vi håber du vil fortsætte som medlem af Alea i 2020</p>

<h3>Mulm af Alex Uth</h3>

<p>Hvis du har bestilt bogen Mulm af Alex Uth, vil den blive sendt med posten
til den adresse du har angivet i tilmeldingen. Du får således ikke pengene retur
for bogen.</p>

<h3>Tilbagebetaling</h3>

<p>Bunkeren begynder processen med at refundere din deltagerbetaling så snart vi
har de relevante oplysninger. Men fordi alting skal gøres manuelt, kan det godt
tage lidt tid endnu. Vi håber fortsat på din forståelse og tålmodighed.</p>

<p>Du skal benytte dette personlige link:
<a href="<?=$this->refund_url?>"><?=$this->refund_url?></a></p>

<p>Hvis du har spørgsmål eller problemer skal du skrive til bunkeren her:
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a> 

<p>Venligste hilsner</p>
<p>Bunkeren og Aleas bestyrelse</p>

<?php } else { ?>
<h2>Fastaval 2020 Refund</h2>

<h3>There was unfortunately an error in the link in the first mail, so here is
a mail with a new link</h3>

<p>Dear participant for Fastaval 2020</p>

<p>Fastaval 2020 is cancelled and The Bunker (the main organizers) is left with
the task of refunding your money. Everybody will get a full refund unless you
have purchased the book Mulm or you wish to become a member of Alea, the
organization behind Fastaval.</p>

<h3>What we need from you</h3>

<p>In the bottom of this mail you will find a link to a personal refund site.
Here you have to give us the information we need in order to pay you back. On
the site you will need to type in the personal code Fastaval assigned you, when 
you signed up for Fastaval 2020. You will find the code inside the mail called, 
”Sign-up for Fastaval 2020”.</p>

<p>If you don’t have the mail you received when you signed up for Fastaval
anymore, please write us at:
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a></p>

<p>NB: The site only works with a Danish bank account. If you are an
international guest at Fastaval please write us at:
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a></p>

<h3>Fastaval’s finances</h3>

<p>Fastaval’s and Alea’s finances are looking strong and paying everybody back
in full will not course any financial problems for future Fastavals. We are very
fortunate in our many collaborators and everybody have been extremely
considerate during this extraordinary situation. All contracts have been
annulled, no questions asked and we have not been met with any demands of
compensation.</p>

<p>Several participants have been asking if they can support Fastaval 2021 with
their payment from Fastaval 2020, but this is really not necessary. We are
nevertheless very touched that so many people are willing to help. Instead you
might consider helping some of our collaborators who are much more affected by
the lockdown – like Danhostel Hobro and Hotel Amerika. The biggest help you can
give Fastaval right now is to renew or purchase a membership to Alea.</p>

<h3>Become a member of Alea!</h3>

<p>Alea is the organization behind Fastaval and under normal circumstances Alea
get the majority of its members when people sign up for Fastaval. We hope that
you still want to support Alea in 2020 even though you won’t get the usual
discount.</p>

<p>Alea need its members fee to run the organization that runs Fastaval. Beside
the administrative part Alea hosts several Fastaval related events during the
year like the general assembly, the scenario- and board game designer weekends
and the organizer weekend. Alea creates stability and continuity between the
annual event Fastaval (with different main organizer groups) and the many
collaborations Fastaval have in Hobro and otherwise.</p>

<p>Besides this, Alea is a member of the Danish larp/roleplay umbrella
organization Bifrost. Bifrost is financially supported by Dansk Ungdoms
Fællessråd and the support is among other thing based on how many members Alea
have. Bifrost gives support to Larp and roleplay all over Denmark 
(including Fastaval) and does important lobbying to benefit the Danish
larp/roleplaying community.</p>

<p>We hope you want to continue as a member of Alea in 2020.</p>

<h3>Mulm by Alex Uth</h3>

<p>If you have purchased the book Mulm by Alex Uth (only in Danish), it will be
sent to the address you gave when you signed up. You will not get a refund on
the book.</p>

<h3>Refund</h3>

<p>The bunker begins to refund your money as quickly as possible when we have
all the information we need from you. But because everything has to be done
manually, we still need both your understanding and patience.</p>

<p>You must use this personal link:
<a href="<?=$this->refund_url?>"><?=$this->refund_url?></a></p>

<p>If you are an international participant, please contact us sooner rather than
later at bunker@fastaval.dk. We want to refund you quickly, but the transactions
between countries can be slower than normal in these circumstances.</p>

<p>Kind regards The Bunker, 2020 and Alea’s board of directors</p>

<?php } ?>

