<?php if ($this->page->danish) { ?>
<h2>Kære deltager på Fastaval.</h2>
<p>Det er med et meget tungt hjerte at bunkeren har besluttet at aflyse Fastaval
2020. Det sker på anbefaling af sundhedsmyndighederne og på baggrund af
statsministerens udmelding onsdag.</P>

<p>Fastaval har aldrig før været aflyst og det betyder, at der at der er en
masse svar vi ikke kan give jer med det samme. I løbet af de næste par uger vil
bunkeren, Aleas bestyrelse og de relevante områdearrangører finde ud af, hvilke
konsekvenser en aflysning kommer til at have på næste års Fastaval og hvordan vi
 sikrer det bedst mulige comeback i 2021.</p>

<p>I vil få jeres billetter tilbagebetalt enten helt eller delvist. Som
udgangspunkt bestræber vi os på at refundere så meget af jeres billetter som
muligt. Men alting afhænger af, hvor meget af de varer vi allerede har bestilt,
vi kan sende retur uden yderlige udgifter. Når vi ved præcis hvor meget du for
refunderet, vil du modtage mail.</p>

<p>Vi har allerede afbestilt Wear for i år, så det vil ikke være muligt at få
sin Fastaval 2020 kop eller t-shirt, pengene vil i stedet blive refunderet
sammen med din billet.</p>

<p>Har du bestilt bogen Mulm af Alex Uth, er vi i gang med at finde en løsning
på at sende dem ud til dig.</p>

<p>Vi har ikke besluttet endnu, hvad der skal ske med årets scenarier og
brætspil. I øjeblikket samarbejder følgende grupper om en løsning; Bunkeren,
Aleas bestyrelse, Otto-juryerne fra i år og 2021 og de scenarie- og
brætspilsansvarlige fra i år og 2021. Vi melder ud både på Facebook, Twitter og
på vores hjemmeside, når vi har en løsning.</p>

<p>Fastaval har mange arrangører som allerede har lagt et stort stykke arbejde.
Bunkeren vil gerne sige jer alle sammen en stor tak, for den kæmpe indsats i har
 ydet. I skal vide, at I er de sejeste og mest dedikerede arrangører en bunker
 kunne ønske sig. Og vi håber at I vil være med til at lave Fastaval
 fremadrettet, selv om i år har været en skuffelse.</p>

 <p>Hvis du har yderlige spørgsmål til Bunkeren, er du velkomne til at skrive
 til os på <a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a>. Vi kan
 ikke love at vi kan svare på alting lige nu, men vi vil gøre vores bedste.</p>

 <p>Tak for din forståelse og tak fordi du var tilmeldt Fastaval 2020. Vi håber
 på at se dig næste år til Fastaval 2021.</P>

<p>Venlig hilsen</p>

<p>Bunkeren 2020: Henrik Krøjmand, Tim Slumstrup Aunkilde, Kathrine Abel,
Marie Oscilowski, Kristoffer Nyrup, Kristian Bach Petersen, Andreas Ravn Skovse
og Ann Kristine Eriksen</p>

<?php } else { ?>
<h2>Dear Fastaval participant</h2>

<p>It is with a heavy heart that the Bunker has decided to cancel Fastaval 2020.
The cancellation comes at the recommendation of the Danish Health Authorities
and following the Danish Prime minister’s recommendations Wednesday.</p>

<p>No Bunker has ever before cancelled a Fastaval so we are in uncharted
territory and there are many answers that we cannot provide you with at the
moment. In the coming weeks, the Bunker together with Alea’s board and the
relevant organizers will establish what consequences the cancellation will have
fore Fastaval 2021, and how we can ensure that Fastaval will get the best
possible comeback in 2021.</p>

<p>You will have your tickets refunded either partly or completely. We will
strive to refund as much as possible. A lot depends on how much of the already
committed expenses we can get refunded from suppliers. When we have an overview,
we will send you a new email with the refund detail.</p>

<p>We have already cancelled our wear order, so it will not be possible to get
your Fastaval 2020 mug or t-shirt. Instead, we will refund your wear purchases
together with your tickets.</p>

<p>If you have ordered the book Mulm by Alex Uth, know that we are working on a
mailing solution together with the publisher.</p>

<p>We are yet to decide what will happen with the games designed for
Fastaval 2020. At the moment the following groups are involved in reaching a
solution: The Bunker, Alea’s board, and the Otto-committees and Scenario- and
Board Game Organizers for both this year and 2021. Once we have reached a
solution, we will let you know through Facebook, Twitter, and Fastaval’s
website.</p>

<p>Fastaval has many organizers who already have done a lot work. The Bunker
would like to extend you all our immense gratitude for all your hard work. We
want you to know that you are the toughest and most dedicated organizers any
Bunker could ever want. We hope you also want to be involved with organizing
Fastaval moving forward, even though this year is a letdown.</p>

<p>If you have any questions to the Bunker, do not hesitate to contact us at
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a>. We cannot promise
you that we are able to answer all your questions right now, but we will do our
best.</p>

<p>We thank you for your understanding and for your signup for Fastaval 2020.
We hope to see you next year for Fastaval 2021.</p>

<p>All best,</p>

<p>The Bunker 2020: Henrik Krøjmand, Tim Slumstrup Aunkilde, Kathrine Abel,
Marie Oscilowski, Kristoffer Nyrup, Kristian Bach Petersen,
Andreas Ravn Skovse, and Ann Kristine Eriksen</p>

<?php } ?>