<?php if ($this->danish) { ?>

<p>Kære deltager til Fastaval 2020</p>

<p>Hvis du allerede har været i kontakt med os og sendt os de relevante
oplysninger, så kan du roligt se bort fra denne mail. Hvis du derimod ikke har
været i kontakt med os eller sendt os oplysninger, så læs med.</p>

<p>Dette er en påmindelse om at bunkeren skal have dine konto-oplysninger, så vi
kan refundere din deltagerbetaling, allersenest 1. juni. Derefter begynder vi at
lukke regnskabet for Fastaval 2020, så bunkeren for 2021 kan komme i gang med
næste års Fastaval. Vi har allerede sendt én mail rundt, ligesom vi har forsøgt
at komme i kontakt med de sidste deltagere telefonisk.</p>

<h3>Hvad skal du gøre</h3>
<p>Du skal gå tilbage i din mail-indbakke (tjek eventuelt spam filteret) og
finde en mail der hedder ’Fastaval 2020 Tilbagebetaling’. Mailen er sendt ud til
alle den 28. marts. Her kan du læse hvordan du sender os de korrekte
informationer. Læs mailen grundigt, så vi slipper for mere ekstraarbejde.</p>

<p>Hvis du ikke har fået mailen ’Fastaval 2020 Tilbagebetaling’ eller hvis du
ikke har en dansk bankkonto, så skal du skrive til os på
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a>.</p>

<p>Hjælp os venligst med at få afsluttet de sidste løse ender for Fastaval 2020
</p>

<p>Venlig hilsen Bunkeren</p>

<?php } else { ?>

<p>Dear Participant</p>

<p>If you have already been in contact with the organizers about your Fastaval
refund, please ignore this email. If you on the other hand have not been in
contact with The Bunker, please read on.</p>

<p>This is a reminder that the organizers need your bank information, in order
to refund your participant fee, at the very latest June the 1st. After this date
we have to close up the finances and books for Fastaval 2020. We have already
sent you one email about the refund.</p>

<h3>What you need to do</h3>
<p>Please go back in your inbox (maybe check the spam filters) and find the
email named ‘Fastaval 2020 refund’. The mail was sent out on March the 28th.
Here you can read about how to send us the correct information. Please read the
mail thoroughly, that we don’t have to do a lot of extra work.</p>

<p>If you have not received an email named ‘Fastaval 2020 refund’ or if you do
not have a Danish bank account, please contact the Bunker at
<a href="mailto:bunker@fastaval.dk">bunker@fastaval.dk</a>.</p>

<p>Please help us close the last loose ends for Fastaval 2020 as soon as
possible</p>

<p>Kind regards, The Bunker</p>

<?php } ?>

